const products = [
    {
        id:1,
        title:"Vancouver",
        category:"",
        description:"",
        price:4500,
        image:"vancouver.png",
        stock:7
    },
    {
        id:2,
        title:"Cleo",
        category:"",
        description:"",
        price:3000,
        image:"cleo.png",
        stock:10
    },
    {
        id:3,
        title:"Denver",
        category:"",
        description:"",
        price:5000,
        image:"denver.png",
        stock:12
    },
    {
        id:4,
        title:"Krono",
        category:"",
        description:"",
        price:4000,
        image:"krono.png",
        stock:8
    },
    {
        id:5,
        title:"Celestina",
        category:"",
        description:"",
        price:3500,
        image:"celestina.png",
        stock:3
    },
    {
        id:6,
        title:"Luli",
        category:"",
        description:"",
        price:2000,
        image:"luli.png",
        stock:5
    },
    {
        id:7,
        title:"Pantu",
        category:"",
        description:"",
        price:2500,
        image:"pantu.png",
        stock:9
    },
    {
        id:8,
        title:"Munich",
        category:"",
        description:"",
        price:4000,
        image:"munich.png",
        stock:7
    },
    {
        id:9,
        title:"Rayo",
        category:"",
        description:"",
        price:3500,
        image:"rayo.png",
        stock:1
    },
    {
        id:10,
        title:"Mochi",
        category:"",
        description:"",
        price:3000,
        image:"mochi.png",
        stock:0
    },
]

export default products